In [1]:
import gensim

In [17]:
import numpy as np

In [145]:
#Import job data
import pandas as pd
from pandas import DataFrame
import json

data = []

with open("/Users/ryancramer/Desktop/handshake_feed1.txt") as f:
    for line in f:
        data.append(json.loads(line))
        
df1 = pd.DataFrame(data)

data = []

with open("/Users/ryancramer/Desktop/courses.txt") as f:
    for line in f:
        data.append(json.loads(line))
        
df2 = pd.DataFrame(data)


df_skill = pd.read_csv("/Users/ryancramer/Desktop/Jupyter Notebook Files/SkillsSet5.csv")

skill5 = list()
df_skill = df_skill["0"]
for word in df_skill:
    #print(word)
    skill5.append(word)

#train_texts = df4['description']

In [147]:
jobs = df1['description']
courses = df2['description']

In [3]:
text = ["natural language processing and machine learning is fun and exciting","This test is very fun"]

# Note the .lower() as upper and lowercase does not matter in our implementation
# [['natural', 'language', 'processing', 'and', 'machine', 'learning', 'is', 'fun', 'and', 'exciting']]
corpus = []
for row in text:
        for word in row.split():
            word = word.lower()
            corpus.append(word)

In [4]:
corpus

['natural',
 'language',
 'processing',
 'and',
 'machine',
 'learning',
 'is',
 'fun',
 'and',
 'exciting',
 'this',
 'test',
 'is',
 'very',
 'fun']

In [276]:
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
def preprocess_data(doc_set):
    """
    Input  : docuemnt list
    Purpose: preprocess text (tokenize, removing stopwords, and stemming)
    Output : preprocessed text
    """
    # initialize regex tokenizer
    tokenizer = RegexpTokenizer(r'\w+')
    # create English stop words list
    en_stop = set(stopwords.words('english'))
    # list for tokenized documents in loop
    texts = []
    # loop through document list
    for i in doc_set:
        # clean and tokenize document string
        raw = i.lower()
        #sents = raw.split(".")
        #tokens = tokenizer.tokenize(raw)
        #text1 = []
        #for sent in sents:
        tokens = tokenizer.tokenize(raw)
            # remove stop words from tokens
        stopped_tokens = [i for i in tokens if not i in en_stop]
            # stem tokens
        alpha_tokens = [i for i in stopped_tokens if i.isalpha() and len(i)<14]
            # alpha tokens only
            #stemmed_tokens = [p_stemmer.stem(i) for i in alpha_tokens]
            # add tokens to list
        texts.append((" ").join(alpha_tokens))
        #texts.append(text1)
    return texts

In [206]:
import re
alphabets= "([A-Za-z])"
prefixes = "(Mr|St|Mrs|Ms|Dr)[.]"
suffixes = "(Inc|Ltd|Jr|Sr|Co)"
starters = "(Mr|Mrs|Ms|Dr|He\s|She\s|It\s|They\s|Their\s|Our\s|We\s|But\s|However\s|That\s|This\s|Wherever)"
acronyms = "([A-Z][.][A-Z][.](?:[A-Z][.])?)"
websites = "[.](com|net|org|io|gov)"

def split_into_sentences(text):
    text = " " + text + "  "
    text = text.replace("\n"," ")
    text = re.sub(prefixes,"\\1<prd>",text)
    text = re.sub(websites,"<prd>\\1",text)
    if "Ph.D" in text: text = text.replace("Ph.D.","Ph<prd>D<prd>")
    text = re.sub("\s" + alphabets + "[.] "," \\1<prd> ",text)
    text = re.sub(acronyms+" "+starters,"\\1<stop> \\2",text)
    text = re.sub(alphabets + "[.]" + alphabets + "[.]" + alphabets + "[.]","\\1<prd>\\2<prd>\\3<prd>",text)
    text = re.sub(alphabets + "[.]" + alphabets + "[.]","\\1<prd>\\2<prd>",text)
    text = re.sub(" "+suffixes+"[.] "+starters," \\1<stop> \\2",text)
    text = re.sub(" "+suffixes+"[.]"," \\1<prd>",text)
    text = re.sub(" " + alphabets + "[.]"," \\1<prd>",text)
    if "”" in text: text = text.replace(".”","”.")
    if "\"" in text: text = text.replace(".\"","\".")
    if "!" in text: text = text.replace("!\"","\"!")
    if "?" in text: text = text.replace("?\"","\"?")
    text = text.replace(".",".<stop>")
    text = text.replace("?","?<stop>")
    text = text.replace("!","!<stop>")
    text = text.replace("<prd>",".")
    sentences = text.split("<stop>")
    sentences = sentences[:-1]
    sentences = [s.strip() for s in sentences]
    return sentences

In [277]:
all_sents = []
for job in jobs:
    hold = (split_into_sentences(job))
    for word in hold:
        all_sents.append(word)

In [278]:
all_sents

['Employer: Tulane University, Howard-Tilton Memorial Library    Expires: 09/21/2019    POSITION SUMMARY: The Library Technician for Domestic Ordering in the Acquisitions and Electronic Resources Department reports to the Manager of Acquisitions and manages all aspects of the EBSCO GOBI firm order process.',
 'Communicates with GOBI representatives to resolve problems.',
 'Handles non-GOBI orders as assigned.',
 'Shares GOBI, OCLC and other library knowledge with library employees.',
 'REQUIRED EDUCATION AND EXPERIENCE: 1.',
 'Bachelor’s degree, or high school diploma/equivalent and 6 years of directly related library experienceREQUIRED KNOWLEDGE, SKILLS, ABILITIES/COMPETENCIES TYPICALLY NEEDED TO PERFORM THIS JOB SUCCESSFULLY:\xa01.',
 'Demonstrated proficiency using Microsoft Excel or other spreadsheet software and a working knowledge of Microsoft Office 2.',
 'Ability to communicate effectively and work with diverse vendors and library personnel with varying levels of experience3.',

In [279]:
jobs_processed = preprocess_data(all_sents)


In [280]:
jobs_processed

['employer tulane university howard tilton memorial library expires position summary library technician domestic ordering acquisitions electronic resources department reports manager acquisitions manages aspects ebsco gobi firm order process',
 'communicates gobi resolve problems',
 'handles non gobi orders assigned',
 'shares gobi oclc library knowledge library employees',
 'required education experience',
 'bachelor degree high school diploma equivalent years directly related library knowledge skills abilities competencies typically needed perform job successfully',
 'demonstrated proficiency using microsoft excel spreadsheet software working knowledge microsoft office',
 'ability communicate effectively work diverse vendors library personnel varying levels',
 'ability prioritize organize manage multiple projects varying',
 'ability work independently good problem solving',
 'ability use good judgment handling',
 'ability pay close attention',
 'ability learn varied computer programs

In [264]:
len(jobs_processed)

17287

In [6]:
core = preprocess_data(text)

In [7]:
core

['natural language processing machine learning fun exciting', 'test fun']

In [258]:
jobs_processed = ['juk j jjjj ', 'mkm jjj kk ll']
print(preprocess_data(jobs_processed))

['employer georgia department public health expires job title biostats analyst phd student emory collaborative closing date time sun pm eastern time salary hourlyjob type part time hourly location peachtree st atlanta georgia division section health protection epithe student employed approximately hours per week georgia department public health seeking highly qualified candidate position professional healthcare worker biostatistics analyst epidemiology drug overdose surveillance section office temporary hourly paid work performing professional health care services positions job established less hours per week eligible benefits position status temporary e scoa georgia department public health dph looking current phd student assist developing methods determine areas georgia vulnerable increased opioid involved drug overdoses infectious disease outbreaks hiv hepatitis associated injection drug use position working cooperative project emory university dph work closely rollins school public

In [304]:
%%time
corpus = []
for row in jobs_processed:
        corpus_hold = list()
        for word in row.split():
            #word = word.lower()
            corpus_hold.append(word)
        corpus.append(corpus_hold)
print(len(corpus))

17287
CPU times: user 112 ms, sys: 72.7 ms, total: 185 ms
Wall time: 256 ms


In [305]:

corpus = corpus[0:200]

In [283]:
settings = {
     # context window +- center word
    'window_size': 2,
   
    # dimensions of word embeddings, also refer to size of hidden layer
    'n': 10,
    
    # number of training epochs
    'epochs': 50,
    
    # learning rate
    'learning_rate': 0.01 
}

In [306]:
%%time
# Initialise object
#850 jobs
#7.36 minutes
#26 seconds per 1000 sentences
w2v = word2vec()
# Numpy ndarray with one-hot representation for [target_word, context_words]
training_data = w2v.generate_training_data(settings, corpus)

CPU times: user 1.58 s, sys: 245 ms, total: 1.82 s
Wall time: 2.29 s


In [77]:
from collections import defaultdict
class word2vec():
    def __init__(self):
        self.n = settings['n']
        self.lr = settings['learning_rate']
        self.epochs = settings['epochs']
        self.window = settings['window_size']
        #self.v_count= 0

    def generate_training_data(self, settings, corpus):
        # Find unique word counts using dictonary
        #word_counts = defaultdict(int)
        word_counts = defaultdict(int)
        for row in corpus:
            for word in row:
                word_counts[word] += 1
        ## How many unique words in vocab? 9
        self.v_count = len(word_counts.keys())
        # Generate Lookup Dictionaries (vocab)
        self.words_list = list(word_counts.keys())
        # Generate word:index
        self.word_index = dict((word, i) for i, word in enumerate(self.words_list))
        # Generate index:word
        self.index_word = dict((i, word) for i, word in enumerate(self.words_list))

        training_data = []
        # Cycle through each sentence in corpus
        for sentence in corpus:
            sent_len = len(sentence)
            # Cycle through each word in sentence
            for i, word in enumerate(sentence):
                # Convert target word to one-hot
                w_target = self.word2onehot(sentence[i])
                # Cycle through context window
                w_context = []
                # Note: window_size 2 will have range of 5 values
                for j in range(i - self.window, i + self.window+1):
                    # Criteria for context word 
                    # 1. Target word cannot be context word (j != i)
                    # 2. Index must be greater or equal than 0 (j >= 0) - if not list index out of range
                    # 3. Index must be less or equal than length of sentence (j <= sent_len-1) - if not list index out of range 
                    if j != i and j <= sent_len-1 and j >= 0:
                        # Append the one-hot representation of word to w_context
                        w_context.append(self.word2onehot(sentence[j]))
                        # print(sentence[i], sentence[j]) 
                        # training_data contains a one-hot representation of the target word and context words
                training_data.append([w_target, w_context])
        return np.array(training_data)

    def word2onehot(self, word):
        # word_vec - initialise a blank vector
        word_vec = [0 for i in range(0, self.v_count)] # Alternative - np.zeros(self.v_count)
        # Get ID of word from word_index
        word_index = self.word_index[word]
        # Change value from 0 to 1 according to ID of the word
        word_vec[word_index] = 1
        return word_vec
        #training
    def train(self, training_data):
        # Initialising weight matrices
        # Both s1 and s2 should be randomly initialised but for this demo, we pre-determine the arrays (getW1 and getW2)
        # getW1 - shape (9x10) and getW2 - shape (10x9)
        #self.w1 = np.array(getW1)
        #self.w2 = np.array(getW2)
        self.w1 = np.random.uniform(-1, 1, (self.v_count, self.n))
        self.w2 = np.random.uniform(-1, 1, (self.n, self.v_count))
        
  
        # Cycle through each epoch
        for i in range(self.epochs):
            # Intialise loss to 0
            self.loss = 0

            # Cycle through each training sample
            # w_t = vector for target word, w_c = vectors for context words
            for w_t, w_c in training_data:
                # Forward pass - Pass in vector for target word (w_t) to get:
                # 1. predicted y using softmax (y_pred) 2. matrix of hidden layer (h) 3. output layer before softmax (u)
                y_pred, h, u = self.forward_pass(w_t)
        
        ##Removed##
        
    def forward_pass(self, x):
        # x is one-hot vector for target word, shape - 9x1
        # Run through first matrix (w1) to get hidden layer - 10x9 dot 9x1 gives us 10x1
        h = np.dot(self.w1.T, x)
        # Dot product hidden layer with second matrix (w2) - 9x10 dot 10x1 gives us 9x1
        u = np.dot(self.w2.T, h)
        # Run 1x9 through softmax to force each element to range of [0, 1] - 1x8
        y_c = self.softmax(u)
        return y_c, h, u
  
    def softmax(self, x):
        e_x = np.exp(x - np.max(x))
        return e_x / e_x.sum(axis=0)
    
    def word_vec(self, word):
        w_index = self.word_index[word]
        v_w = self.w1[w_index]
        return v_w
    
    # Input vector, returns nearest word(s)
    '''
    def vec_sim(self, word, top_n):
        v_w1 = self.word_vec(word)
        word_sim = {}

        for i in range(self.v_count):
            # Find the similary score for each word in vocab
            v_w2 = self.w1[i]
            theta_sum = np.dot(v_w1, v_w2)
            theta_den = np.linalg.norm(v_w1) * np.linalg.norm(v_w2)
            theta = theta_sum / theta_den

            word = self.index_word[i]
            word_sim[word] = theta

        words_sorted = sorted(word_sim.items(), key=lambda kv: kv[1], reverse=True)

        for word, sim in words_sorted[:top_n]:
            print(word, sim)
    '''
    def vec_sim(self, v_w1, top_n):
        #v_w1 = self.word_vec(word)
        word_sim = {}

        for i in range(self.v_count):
            # Find the similary score for each word in vocab
            v_w2 = self.w1[i]
            theta_sum = np.dot(v_w1, v_w2)
            theta_den = np.linalg.norm(v_w1) * np.linalg.norm(v_w2)
            theta = theta_sum / theta_den

            word = self.index_word[i]
            word_sim[word] = theta

        words_sorted = sorted(word_sim.items(), key=lambda kv: kv[1], reverse=True)

        for word, sim in words_sorted[:top_n]:
            print(word, sim)

In [62]:
wordss = defaultdict(int)
for row in corpus:
            for word in row:
                wordss[word] += 1
wordss

defaultdict(int,
            {'natural': 1,
             'language': 1,
             'processing': 1,
             'machine': 1,
             'learning': 1,
             'fun': 2,
             'exciting': 1,
             'test': 1})

In [44]:
training_data

array([[list([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        list([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])],
       [list([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        list([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])],
       [list([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        list([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])],
       [list([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        list([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 

In [307]:
%%time
# Training
#necessary idk
#time for 200 = 24.7 seconds
w2v.train(training_data)

CPU times: user 48 s, sys: 177 ms, total: 48.2 s
Wall time: 24.7 s


In [309]:
#print(w2v.word_vec("test"))

In [67]:
#print(w2v.word_index)

In [310]:
#w2v.vec_sim("test", 3)

In [73]:
sum2 = (w2v.word_vec("test") + w2v.word_vec("fun"))/2

In [74]:
sum2

array([ 0.74395021,  0.60418814,  0.18033204, -0.88356649, -0.14975516,
        0.08311769, -0.50146759,  0.06790034,  0.77264497, -0.30930982])

In [81]:
w2v.vec_sim(sum2, 3)

test 0.33936690223783916
processing 0.09300705032232416
exciting 0.07173346971881343


In [ ]:
#model

In [84]:
sentence14 = ["test", "test"]

In [85]:
w2v.train(sentence14)

ValueError: too many values to unpack (expected 2)

In [328]:
count = 0
hold = np.empty(10)
for word in sentence14:
    hold = hold + w2v.word_vec(word)
    #print(type(hold))
    count = count +1
hold = hold / count

In [327]:
hold

['Employer: Georgia Department of Public Health    Expires: 01/28/2019    Job Title: Biostats Analyst PHD student ( Emory Collaborative)  Closing Date/Time:   Sun.',
 '01/27/19 11:59 PM Eastern Time   Salary:   $15.',
 '00 - $18.',
 '00 HourlyJob Type:  Part Time Hourly  Location:  2 Peachtree St, Atlanta, Georgia Division/Section: Health Protection/EPIThe student will be employed for approximately 10 hours per week.',
 'The Georgia Department of Public Health is seeking a highly qualified candidate for the position of Professional Healthcare Worker - Biostatistics Analyst in the Epidemiology, Drug Overdose Surveillance Section/Office.',
 'This is temporary or hourly paid work performing professional health care services.',
 'Positions in this job are established for less than 30 hours per week and are not eligible for benefits if the position status is temporary (i.e., SCOA 513).',
 'The Georgia Department of Public Health (DPH) is looking for a current PhD student to assist in develo

In [326]:
sentence15 = ["test", "fun"]

In [102]:
count = 0
hold2 = np.empty(10)
for word in sentence15:
    hold2 = hold2 + w2v.word_vec(word)
    #print(type(hold))
    count = count +1
hold2 = hold / count

In [124]:
hold2

array([ 0.32512966, -0.32179241,  0.4392189 , -0.34977247, -0.61276376,
        0.44928205, -0.24835688,  0.13656006, -0.45181422,  0.63554948])

In [138]:
sentence16 = ["language", "natural","test"]

In [140]:
count = 0
hold3 = np.empty(10)
for word in sentence16:
    hold3 = hold3 + w2v.word_vec(word)
    #print(type(hold))
    count = count +1
hold3 = hold / count

In [139]:
hold3

array([ 0.32512966, -0.32179241,  0.4392189 , -0.34977247, -0.61276376,
        0.44928205, -0.24835688,  0.13656006, -0.45181422,  0.63554948])

In [141]:
hold3

array([ 0.21675311, -0.21452828,  0.2928126 , -0.23318165, -0.40850917,
        0.29952137, -0.16557126,  0.09104004, -0.30120948,  0.42369965])

In [123]:
#from sklearn.metrics.pairwise import pairwise_distances

In [122]:
#sim = 1-pairwise_distances(hold,hold2, metric='cosine')

In [142]:
jobs = [hold,hold2,hold3]

In [144]:
vec_sim(hold2,jobs,3)

[ 0.65025933 -0.64358483  0.8784378  -0.69954494 -1.22552751  0.89856411
 -0.49671377  0.27312011 -0.90362845  1.27109896]
3.5804729789549343
3.5804729789549343
[ 0.32512966 -0.32179241  0.4392189  -0.34977247 -0.61276376  0.44928205
 -0.24835688  0.13656006 -0.45181422  0.63554948]
1.7902364894774672
1.7902364894774672
[ 0.21675311 -0.21452828  0.2928126  -0.23318165 -0.40850917  0.29952137
 -0.16557126  0.09104004 -0.30120948  0.42369965]
1.1934909929849782
1.193490992984978
[(2, 1.0000000000000002), (0, 1.0), (1, 1.0)]
2 1.0000000000000002
0 1.0
1 1.0


In [311]:
def ngram(doc_set):
    texts = []
    for i in doc_set:
        text_with_grams = []
        count = 1
        holder = ""
        words = i.split()
        for word in words:
            if count == 1:
                holder = word
            else:  
                text_with_grams.append(holder + " " + word)
                text_with_grams.append(holder)
                if count == len(words):
                    text_with_grams.append(word)
                holder = word
            count = count + 1
        texts.append(text_with_grams)
    return texts

In [312]:
def SkillConverter(jobs,skills):
    texts = []
    for job in jobs:
        skill_text = []
        skip_gram = False
        for word in job:
            if skip_gram == True:
                skip_gram = False
                continue
            elif skip_gram == False and word in skills:
                skill_text.append(word)
                skip_gram = True
        texts.append((" ").join(skill_text))
    return texts

In [313]:
jobs_ngram = ngram(jobs_processed)

In [314]:
jobs_skills = SkillConverter(jobs_ngram,skill5)

In [317]:
jobs_skills = jobs_skills[0:100]

In [359]:
jobs_skills[40]

'experience shell scripting python scripting java programming use oracle enterprise unix linux large knowledge json pdf file communication verbal'

In [323]:
jobs_skills[0:1]

['employer university memorial library position summary library technician domestic electronic department manager order']

In [390]:
all_sums = []
for jobs in jobs_skills:
    count = 0
    hold1 = np.empty(10)
    
    for word in jobs.split():
        #print(word)
        hold1 = hold1 + w2v.word_vec(word)
        
        print(type(hold1))
        count = count +1
    if count != 0:
        hold1 = hold1 / count
    all_sums.append(hold1)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.nd

In [391]:
len(all_sums)

100

In [341]:
def vec_sim(v_w1, jobss, top_n):
        #v_w1 = self.word_vec(word)
        word_sim = {}
        count = 0
        for i in jobss:
            #print(i)
            # Find the similary score for each word in vocab
            v_w2 = i
            theta_sum = np.dot(v_w1, v_w2)
            print(theta_sum)
            theta_den = np.linalg.norm(v_w1) * np.linalg.norm(v_w2)
            print(theta_den)
            theta = theta_sum / theta_den
            
            
            #word = self.index_word[i]
            word_sim[count] = theta
            count = count +1

        words_sorted = sorted(word_sim.items(), key=lambda kv: kv[1], reverse=True)
        print(words_sorted)
        for word, sim in words_sorted[:top_n]:
            print(word, sim)

In [372]:
vec_sim(all_sums[6],all_sums,3)

0.02466040905637714
0.02466040905637714
0.32058531773290283
0.32058531773290283
0.22458314865051018
1.0153184006349618
0.10686177257763428
0.10686177257763428
0.32058531773290283
0.32058531773290283
0.029144119793900258
0.029144119793900258
0.040073164716612854
0.040073164716612854
0.06411706354658056
0.06411706354658056
0.08014632943322571
0.08014632943322571
0.08014632943322571
0.08014632943322571
0.08014632943322571
0.08014632943322571
0.10686177257763428
0.10686177257763428
0.08014632943322571
0.08014632943322571
0.05343088628881714
0.05343088628881714
0.035620590859211425
0.035620590859211425
0.06411706354658056
0.06411706354658056
0.05343088628881714
0.05343088628881714
0.16029265886645142
0.16029265886645142
0.32058531773290283
0.32058531773290283
0.05343088628881714
0.05343088628881714
2.6045903809829554
8.37479221840949
0.10686177257763428
0.10686177257763428
0.020036582358306427
0.020036582358306427
0.04579790253327183
0.04579790253327183
0.06411706354658056
0.064117063546580

In [392]:
all_sums_matrix = np.column_stack(all_sums)

In [362]:
from sklearn.metrics.pairwise import pairwise_distances

In [374]:
#from sklearn.metrics.pairwise import cosine_similarity

In [393]:
sim = 1-pairwise_distances(all_sums,all_sums, metric='cosine')

In [381]:
#sim2 = cosine_similarity(all_sums)

In [386]:
all_sums

[array([-0.00393166, -0.02290929,  0.09196926,  0.01663039,  0.04805779,
        -0.02598311,  0.00622926,  0.01133744, -0.0073445 ,  0.05190832]),
 array([-0.05111162, -0.29782072,  1.19560032,  0.21619502,  0.62475123,
        -0.33778049,  0.08098036,  0.14738675, -0.09547852,  0.6748081 ]),
 array([ 3.02368596,  1.28593718,  1.89545352,  1.01800165, -1.20456786,
         0.58726102,  1.67400428,  1.7334997 ,  1.43022194,  0.80662546]),
 array([-0.01703721, -0.09927357,  0.39853344,  0.07206501,  0.20825041,
        -0.1125935 ,  0.02699345,  0.04912892, -0.03182617,  0.22493603]),
 array([-0.05111162, -0.29782072,  1.19560032,  0.21619502,  0.62475123,
        -0.33778049,  0.08098036,  0.14738675, -0.09547852,  0.6748081 ]),
 array([-0.00464651, -0.02707461,  0.10869094,  0.01965409,  0.05679557,
        -0.03070732,  0.00736185,  0.0133988 , -0.00867987,  0.06134619]),
 array([-0.00638895, -0.03722759,  0.14945004,  0.02702438,  0.0780939 ,
        -0.04222256,  0.01012255,  0.01

In [370]:
len(jobs_skills)

100