In [1]:
import numpy as np

In [9]:
oneDim = np.array([1.0,2,3,4,5])
print(oneDim)
print("#Dimensions =", oneDim.ndim)
print("Dimension =", oneDim.shape)
print("Size =", oneDim.size)
print("Array type =", oneDim.dtype)


[1. 2. 3. 4. 5.]
#Dimensions = 1
Dimension = (5,)
Size = 5
Array type = float64


In [10]:
twoDim = np.array([[1,2],[3,4],[5,6],[7,8]])  # a two-dimensional array (matrix)
print(twoDim)
print("#Dimensions =", twoDim.ndim)
print("Dimension =", twoDim.shape)
print("Size =", twoDim.size)
print("Array type =", twoDim.dtype)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
#Dimensions = 2
Dimension = (4, 2)
Size = 8
Array type = int64


In [11]:
arrFromTuple = np.array([(1,'a',3.0),(2,'b',3.5)])  # create ndarray from tuple
print(arrFromTuple)
print("#Dimensions =", arrFromTuple.ndim)
print("Dimension =", arrFromTuple.shape)
print("Size =", arrFromTuple.size)

[['1' 'a' '3.0']
 ['2' 'b' '3.5']]
#Dimensions = 2
Dimension = (2, 3)
Size = 6


In [20]:
print(np.random.rand(5))      # random numbers from a uniform distribution between [0,1]
print(np.random.randn(5))     # random numbers from a normal distribution
print(np.arange(-10,10,2))    # similar to range, but returns ndarray instead of list
print(np.arange(12).reshape(3,4))  # reshape to a matrix
print(np.linspace(0,1,10))    # split interval [0,1] into 10 equally separated values
print(np.logspace(-3,3,7))    # create ndarray with values from 10^-3 to 10^3

[0.57388809 0.99316903 0.91746617 0.38681977 0.74695317]
[-0.04311471  0.18153922 -1.20206634 -1.01842922 -0.23048518]
[-10  -8  -6  -4  -2   0   2   4   6   8]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03]


In [21]:
print(np.zeros((2,3)))        # a matrix of zeros
print(np.ones((3,2)))         # a matrix of ones
print(np.eye(3))              # a 3 x 3 identity matrix (diagonal elements)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
x = np.array([1,2,3,4,5])

print(x + 1)      # addition
print(x - 1)      # subtraction
print(x * 2)      # multiplication
print(x // 2)     # integer division
print(x ** 2)     # square
print(x % 2)      # modulo  
print(1 / x)      # division

[2 3 4 5 6]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0 1 1 2 2]
[ 1  4  9 16 25]
[1 0 1 0 1]
[1.         0.5        0.33333333 0.25       0.2       ]


In [23]:
x = np.array([2,4,6,8,10])
y = np.array([1,2,3,4,5])

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x // y)
print(x ** y)

[ 3  6  9 12 15]
[1 2 3 4 5]
[ 2  8 18 32 50]
[2. 2. 2. 2. 2.]
[2 2 2 2 2]
[     2     16    216   4096 100000]


In [24]:
x = np.arange(-5,5)
print(x)

y = x[3:5]     # y is a slice, i.e., pointer to a subarray in x
print(y)

y[:] = 1000    # modifying the value of y will change x
print(y)
print(x)

z = x[3:5].copy()   # makes a copy of the subarray
print(z)
z[:] = 500          # modifying the value of z will not affect x
print(z)
print(x)


[-5 -4 -3 -2 -1  0  1  2  3  4]
[-2 -1]
[1000 1000]
[  -5   -4   -3 1000 1000    0    1    2    3    4]
[1000 1000]
[500 500]
[  -5   -4   -3 1000 1000    0    1    2    3    4]


In [25]:
my2dlist = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]   # a 2-dim list
print(my2dlist)
print(my2dlist[2])        # access the third sublist
print(my2dlist[:][2])     # can't access third element of each sublist
# print(my2dlist[:,2])    # this will cause syntax error

my2darr = np.array(my2dlist)
print(my2darr)
print(my2darr[2][:])      # access the third row
print(my2darr[2,:])       # access the third row
print(my2darr[:][2])      # access the third row (similar to 2d list)
print(my2darr[:,2])       # access the third column
print(my2darr[:2,2:])     # access the first two rows & last two columns

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]
[9, 10, 11, 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 9 10 11 12]
[ 9 10 11 12]
[ 9 10 11 12]
[ 3  7 11]
[[3 4]
 [7 8]]


In [26]:
my2darr = np.arange(1,13,1).reshape(3,4)
print(my2darr)

divBy3 = my2darr[my2darr % 3 == 0]
print(divBy3, type(divBy3))

divBy3LastRow = my2darr[2:, my2darr[2,:] % 3 == 0]
print(divBy3LastRow)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 3  6  9 12] <class 'numpy.ndarray'>
[[ 9 12]]


In [27]:
my2darr = np.arange(1,13,1).reshape(4,3)
print(my2darr)

indices = [2,1,0,3]    # selected row indices
print(my2darr[indices,:])

rowIndex = [0,0,1,2,3]     # row index into my2darr
columnIndex = [0,2,0,1,2]  # column index into my2darr
print(my2darr[rowIndex,columnIndex])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]
 [10 11 12]]
[ 1  3  4  8 12]


In [30]:
y = np.array([-1.4, 0.4, -3.2, 2.5, 3.4])    # generate a random vector
print(y)

print(np.abs(y))          # convert to absolute values
print(np.sqrt(abs(y)))    # apply square root to each element
print(np.sign(y))         # get the sign of each element
print(np.exp(y))          # apply exponentiation
print(np.sort(y))         # sort array

[-1.4  0.4 -3.2  2.5  3.4]
[1.4 0.4 3.2 2.5 3.4]
[1.18321596 0.63245553 1.78885438 1.58113883 1.84390889]
[-1.  1. -1.  1.  1.]
[ 0.24659696  1.4918247   0.0407622  12.18249396 29.96410005]
[-3.2 -1.4  0.4  2.5  3.4]


In [31]:
x = np.arange(-2,3)
y = np.random.randn(5)
print(x)
print(y)

print(np.add(x,y))           # element-wise addition       x + y
print(np.subtract(x,y))      # element-wise subtraction    x - y
print(np.multiply(x,y))      # element-wise multiplication x * y
print(np.divide(x,y))        # element-wise division       x / y
print(np.maximum(x,y))       # element-wise maximum        max(x,y)

[-2 -1  0  1  2]
[ 0.30605873 -0.57987504  0.59885447  0.67166257 -1.11349225]
[-1.69394127 -1.57987504  0.59885447  1.67166257  0.88650775]
[-2.30605873 -0.42012496 -0.59885447  0.32833743  3.11349225]
[-0.61211745  0.57987504  0.          0.67166257 -2.2269845 ]
[-6.53469358  1.72450947  0.          1.48884283 -1.79615081]
[ 0.30605873 -0.57987504  0.59885447  1.          2.        ]


In [32]:
y = np.array([-3.2, -1.4, 0.4, 2.5, 3.4])    # generate a random vector
print(y)

print("Min =", np.min(y))             # min 
print("Max =", np.max(y))             # max 
print("Average =", np.mean(y))        # mean/average
print("Std deviation =", np.std(y))   # standard deviation
print("Sum =", np.sum(y))             # sum

print("Index of Min = ", np.argmin(y))
print("Index of Max = ", np.argmax(y))


[-3.2 -1.4  0.4  2.5  3.4]
Min = -3.2
Max = 3.4
Average = 0.34000000000000014
Std deviation = 2.432776191925595
Sum = 1.7000000000000006
Index of Min =  0
Index of Max =  4


In [33]:
# Q: what's the difference between np.max and np.maximum?

y = np.arange(1,13,1).reshape(4,3)
print(y)
#np.maximum(y)
print(np.max(y, axis=0))
print(np.max(y, axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[10 11 12]
[ 3  6  9 12]


In [45]:
X = np.random.randn(2,3)    # create a 2 x 3 random matrix
print(X)
print(X.T)             # matrix transpose operation X^T

y = np.random.randn(3) # random vector 
print(y)
print(X.dot(y))        # matrix-vector multiplication  X * y
print(X.dot(X.T))      # matrix-matrix multiplication  X * X^T
print(X.T.dot(X))      # matrix-matrix multiplication  X^T * X

[[-0.42458029  0.44948732  0.73268665]
 [ 0.99743576  1.80151269  1.61680139]]
[[-0.42458029  0.99743576]
 [ 0.44948732  1.80151269]
 [ 0.73268665  1.61680139]]
[-0.67618599  0.8118353   0.37359347]
[0.92573186 1.39210594]
[[0.919137   1.57087434]
 [1.57087434 6.85437279]]
[[1.17514652 1.60604972 1.30157122]
 [1.60604972 3.44748681 3.24202158]
 [1.30157122 3.24202158 3.15087647]]


In [46]:
X = np.random.randn(5,3)
print(X)

C = X.T.dot(X)               # C = X^T * X is a square matrix

invC = np.linalg.inv(C)      # inverse of a square matrix
print(invC)
detC = np.linalg.det(C)      # determinant of a square matrix
print(detC)
S, U = np.linalg.eig(C)      # eigenvalue S and eigenvector U of a square matrix
print(S)
print(U)


[[ 0.02299718  1.42525511  0.90152162]
 [-0.52071213  0.05200784  0.41418782]
 [ 0.99601985  1.27111181  1.11607369]
 [ 0.36760504  1.04587241 -0.7238281 ]
 [ 0.32798315  1.61231721 -1.35701481]]
[[ 1.19010922 -0.35623101 -0.07027365]
 [-0.35623101  0.24300515  0.02756004]
 [-0.07027365  0.02756004  0.22207399]]
28.313426339420843
[0.76083756 8.07648904 4.60763298]
[[-0.94613339  0.3141438   0.07839178]
 [ 0.31637109  0.94847405  0.01750192]
 [ 0.06885445 -0.04136005  0.99676899]]


In [47]:
a = np.array([[1,4,2],[3,1,2]])
print(a)

print(np.sort(a))                # sort along the last axis
#print(np.sort(a, axis=1))

print(np.sort(a, axis=None))     # sort the flattened array

print(np.sort(a, axis=0))        # sort along the first axis

[[1 4 2]
 [3 1 2]]
[[1 2 4]
 [1 2 3]]
[1 1 2 2 3 4]
[[1 1 2]
 [3 4 2]]


In [48]:
# change the shape of an array

a = np.array([[0,0],
              [1,1],
              [2,2]])
print(a)
print(a.shape)

[[0 0]
 [1 1]
 [2 2]]
(3, 2)


In [49]:
print(a.ravel())   # flattened array
print(np.ravel(a))

[0 0 1 1 2 2]
[0 0 1 1 2 2]


In [50]:
# The reshape function returns its argument with a modified shape, 
# whereas the ndarray.resize method modifies the array itself:
a.reshape(2,3)
print(a)
a.resize((2,3))
print(a)

[[0 0]
 [1 1]
 [2 2]]
[[0 0 1]
 [1 2 2]]


In [51]:
# If a dimension is given as -1 in a reshaping operation, 
# the other dimensions are automatically calculated:
print(a.reshape(3,-1))
print(a.reshape((-1)))

[[0 0]
 [1 1]
 [2 2]]
[0 0 1 1 2 2]


In [52]:
# Stacking together different arrays
a = np.array([[0,0],
              [1,1],
              [2,2]])
b = np.array([[3,3],
              [4,4],
              [5,5]])

print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]
[[0 0 3 3]
 [1 1 4 4]
 [2 2 5 5]]


In [53]:
# concatenate allows for an optional arguments 
# giving the number of the axis along which the concatenation should happen.
print(np.concatenate((a,b), axis=0))
print(np.concatenate((a,b), axis=1))
print(np.concatenate((a,b), axis=None))

[[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]
[[0 0 3 3]
 [1 1 4 4]
 [2 2 5 5]]
[0 0 1 1 2 2 3 3 4 4 5 5]


In [54]:
a = np.array([1,2,3,4])

print(np.cumsum(a)) # cumulative sum
print(np.cumprod(a)) # cumulative product

[ 1  3  6 10]
[ 1  2  6 24]


In [56]:
# Indexing with Arrays of Indices
a = np.arange(12)**2                       # the first 12 square numbers
print(a)

i = np.array( [ 1,1,3,8,5 ] )              # an array of indices
print(a[i])                                       # the elements of a at the positions i

j = np.array( [ [ 3, 4], [ 9, 7 ] ] )      # a bidimensional array of indices
print(a[j])                                       # the same shape as j

[  0   1   4   9  16  25  36  49  64  81 100 121]
[ 1  1  9 64 25]
[[ 9 16]
 [81 49]]


In [57]:
# You can also use indexing with arrays as a target to assign to:
a = np.arange(5)
print(a)

a[[1,3,4]] = 0
print(a)

[0 1 2 3 4]
[0 0 2 0 0]


In [58]:
# Indexing with Boolean Arrays
a = np.arange(5)
print(a)
b = a > 2
print(b)
print(a[b])

[0 1 2 3 4]
[False False False  True  True]
[3 4]


In [59]:
a = np.array([1,0,2,3,4], dtype=np.float)
# Q1: Given an array, standardize the array:
mean = np.mean(a)
std = np.std(a)
a = (a - mean) / std
print(a)

[-0.70710678 -1.41421356  0.          0.70710678  1.41421356]


In [60]:
a = np.array([1,0,2,3,4], dtype=np.float)
# Q2: only standardize the non-zero elements and update them:
mean = np.mean(a[a > 0])
std = np.std(a[a > 0])
a[a > 0] = (a[a > 0] - mean) / std
print(a)

[-1.34164079  0.         -0.4472136   0.4472136   1.34164079]
